/**
 * Package AI PDF Generator
 * Generates PDF from AI-generated package content
 */

import PDFDocument from 'pdfkit';
import Package from '../models/package.model.js';
import logger from '../config/logger.js';

class PackageAIPDFGenerator {
  /**
   * Generate PDF for a package with AI content
   * @param {string} packageId - Package ID
   * @returns {Promise<Buffer>} PDF buffer
   */
  async generatePackagePDF(packageId) {
    const pkg = await Package.findById(packageId);

    if (!pkg) {
      throw new Error('Package not found');
    }

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 50, bottom: 50, left: 50, right: 50 },
        });

        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(buffers);
          resolve(pdfBuffer);
        });
        doc.on('error', reject);

        // Header
        doc
          .fontSize(24)
          .font('Helvetica-Bold')
          .text(pkg.name || 'Travel Package', { align: 'center' })
          .moveDown();

        if (pkg.destination) {
          doc
            .fontSize(16)
            .font('Helvetica')
            .text(`Destination: ${pkg.destination}`, { align: 'center' })
            .moveDown();
        }

        // Description
        if (pkg.description) {
          doc
            .fontSize(14)
            .font('Helvetica-Bold')
            .text('Package Description', { underline: true })
            .moveDown(0.5)
            .fontSize(11)
            .font('Helvetica')
            .text(pkg.description, {
              align: 'justify',
              lineGap: 5,
            })
            .moveDown();
        }

        // Highlights
        if (pkg.highlights && pkg.highlights.length > 0) {
          doc
            .fontSize(14)
            .font('Helvetica-Bold')
            .text('Package Highlights', { underline: true })
            .moveDown(0.5)
            .fontSize(11)
            .font('Helvetica');

          pkg.highlights.forEach((highlight) => {
            doc.text(`• ${highlight}`, { indent: 20 });
          });
          doc.moveDown();
        }

        // Itinerary Overview
        if (pkg.itinerary) {
          doc
            .fontSize(14)
            .font('Helvetica-Bold')
            .text('Itinerary Overview', { underline: true })
            .moveDown(0.5)
            .fontSize(11)
            .font('Helvetica')
            .text('A detailed day-by-day itinerary is included in this package.', {
              align: 'justify',
            })
            .moveDown();
        }

        // Inclusions
        if (pkg.inclusions && pkg.inclusions.length > 0) {
          doc
            .fontSize(14)
            .font('Helvetica-Bold')
            .text('What\'s Included', { underline: true })
            .moveDown(0.5)
            .fontSize(11)
            .font('Helvetica');

          pkg.inclusions.forEach((inclusion) => {
            doc.text(`✓ ${inclusion}`, { indent: 20 });
          });
          doc.moveDown();
        }

        // Exclusions
        if (pkg.exclusions && pkg.exclusions.length > 0) {
          doc
            .fontSize(14)
            .font('Helvetica-Bold')
            .text('What\'s Not Included', { underline: true })
            .moveDown(0.5)
            .fontSize(11)
            .font('Helvetica');

          pkg.exclusions.forEach((exclusion) => {
            doc.text(`✗ ${exclusion}`, { indent: 20 });
          });
          doc.moveDown();
        }

        // Package Details
        doc
          .fontSize(14)
          .font('Helvetica-Bold')
          .text('Package Details', { underline: true })
          .moveDown(0.5)
          .fontSize(11)
          .font('Helvetica');

        if (pkg.duration) {
          doc.text(`Duration: ${pkg.duration} days`);
        }
        if (pkg.price) {
          doc.text(`Price: ₹${pkg.price.toLocaleString('en-IN')}`);
        }
        if (pkg.maxGroupSize) {
          doc.text(`Max Group Size: ${pkg.maxGroupSize} people`);
        }
        if (pkg.difficulty) {
          doc.text(`Difficulty: ${pkg.difficulty.charAt(0).toUpperCase() + pkg.difficulty.slice(1)}`);
        }

        // Footer
        doc
          .fontSize(10)
          .font('Helvetica-Oblique')
          .text(
            'Generated by Trip Sky Way - AI-Powered Travel Packages',
            { align: 'center' }
          );

        doc.end();
      } catch (error) {
        logger.error('Error generating PDF:', error);
        reject(error);
      }
    });
  }
}

export default new PackageAIPDFGenerator();

