/**
 * Sample data for packages
 * This should be moved to an API service in a real application
 */

export const SAMPLE_PACKAGES = [
  {
    id: 1,
    name: 'Paris Romance Getaway',
    category: 'Honeymoon',
    region: 'Europe',
    duration: '5 Days / 4 Nights',
    price: '$2,499',
    rating: 4.8,
    reviews: 24,
    destinations: ['Paris', 'Versailles'],
    activities: ['Eiffel Tower Tour', 'Seine River Cruise', 'Louvre Museum'],
    accommodation: '4-Star Hotel',
    transport: 'Flight + Transfers',
    images: [],
    status: 'published',
    createdDate: '2024-08-15',
    updatedDate: '2024-10-18',
    bookings: 8,
    description:
      'Experience the magic of Paris with your loved one. Romantic dinners, iconic landmarks, and unforgettable memories.',
    itinerary: {
      first_day: 'Arrival in Paris, check-in at hotel, evening Seine River Cruise',
      middle_days: {
        day_1: 'Eiffel Tower tour and romantic dinner',
        day_2: 'Louvre Museum visit and city exploration',
        day_3: 'Day trip to Versailles Palace',
      },
      last_day: 'Morning shopping, departure',
    },
    itineraryTitles: {
      first_day: 'Arrival Day',
      middle_days: {
        day_1: 'Day 1: Paris Landmarks',
        day_2: 'Day 2: Art & Culture',
        day_3: 'Day 3: Versailles Excursion',
      },
      last_day: 'Departure Day',
    },
  },
  {
    id: 2,
    name: 'Bali Family Adventure',
    category: 'Family',
    region: 'Asia',
    duration: '7 Days / 6 Nights',
    price: '$1,899',
    rating: 4.6,
    reviews: 18,
    destinations: ['Bali', 'Ubud', 'Seminyak'],
    activities: ['Beach Activities', 'Temple Tours', 'Rice Terrace Trekking', 'Water Sports'],
    accommodation: '3-Star Resort',
    transport: 'Flight + Transfers',
    images: [],
    status: 'published',
    createdDate: '2024-07-20',
    updatedDate: '2024-10-17',
    bookings: 12,
    description:
      'Perfect family vacation with beaches, culture, and adventure. Kid-friendly activities and comfortable accommodations.',
    itinerary: {
      first_day: 'Arrival in Bali, check-in at resort',
      middle_days: {
        day_1: 'Beach activities in Seminyak',
        day_2: 'Temple tours in Ubud',
        day_3: 'Rice terrace trekking',
        day_4: 'Water sports day',
        day_5: 'Cultural village visit',
      },
      last_day: 'Free morning, departure',
    },
    itineraryTitles: {
      first_day: 'Arrival Day',
      middle_days: {
        day_1: 'Day 1: Beach Fun',
        day_2: 'Day 2: Cultural Exploration',
        day_3: 'Day 3: Nature Trek',
        day_4: 'Day 4: Adventure Sports',
        day_5: 'Day 5: Village Life',
      },
      last_day: 'Departure Day',
    },
  },
  {
    id: 3,
    name: 'Dubai Luxury Escape',
    category: 'Corporate',
    region: 'Middle East',
    duration: '4 Days / 3 Nights',
    price: '$3,299',
    rating: 4.9,
    reviews: 32,
    destinations: ['Dubai', 'Abu Dhabi'],
    activities: ['Desert Safari', 'Burj Khalifa', 'Shopping Mall Tour', 'Beach Resort'],
    accommodation: '5-Star Luxury Hotel',
    transport: 'Flight + Premium Transfers',
    images: [],
    status: 'published',
    createdDate: '2024-06-10',
    updatedDate: '2024-10-16',
    bookings: 15,
    description: 'Luxury experience in Dubai with world-class hotels, shopping, and entertainment.',
    itinerary: {
      first_day: 'Arrival in Dubai, check-in at luxury hotel',
      middle_days: {
        day_1: 'Desert safari experience',
        day_2: 'Burj Khalifa visit and shopping',
      },
      last_day: 'Beach resort relaxation, departure',
    },
    itineraryTitles: {
      first_day: 'Arrival Day',
      middle_days: {
        day_1: 'Day 1: Desert Adventure',
        day_2: 'Day 2: City Highlights',
      },
      last_day: 'Departure Day',
    },
  },
  {
    id: 4,
    name: 'Tokyo Cultural Journey',
    category: 'Adventure',
    region: 'Asia',
    duration: '6 Days / 5 Nights',
    price: '$2,199',
    rating: 4.7,
    reviews: 21,
    destinations: ['Tokyo', 'Kyoto', 'Osaka'],
    activities: ['Temple Visits', 'Traditional Tea Ceremony', 'Sumo Wrestling', 'Street Food Tour'],
    accommodation: '4-Star Hotel',
    transport: 'Flight + JR Pass',
    images: [],
    status: 'draft',
    createdDate: '2024-09-01',
    updatedDate: '2024-10-19',
    bookings: 0,
    description: 'Immerse yourself in Japanese culture with temples, traditions, and modern cities.',
    itinerary: {
      first_day: 'Arrival in Tokyo, hotel check-in',
      middle_days: {
        day_1: 'Temple visits in Tokyo',
        day_2: 'Traditional tea ceremony',
        day_3: 'Sumo wrestling event',
        day_4: 'Street food tour in Osaka',
      },
      last_day: 'Free morning, departure',
    },
    itineraryTitles: {
      first_day: 'Arrival Day',
      middle_days: {
        day_1: 'Day 1: Tokyo Temples',
        day_2: 'Day 2: Cultural Experience',
        day_3: 'Day 3: Sumo Spectacle',
        day_4: 'Day 4: Osaka Food Tour',
      },
      last_day: 'Departure Day',
    },
  },
  {
    id: 5,
    name: 'Maldives Paradise Resort',
    category: 'Honeymoon',
    region: 'Asia',
    duration: '5 Days / 4 Nights',
    price: '$4,599',
    rating: 5.0,
    reviews: 45,
    destinations: ['Maldives', 'Male'],
    activities: ['Snorkeling', 'Diving', 'Island Hopping', 'Spa & Wellness'],
    accommodation: '5-Star Water Bungalow',
    transport: 'Flight + Speedboat',
    images: [],
    status: 'published',
    createdDate: '2024-05-15',
    updatedDate: '2024-10-15',
    bookings: 22,
    description:
      'Ultimate tropical paradise with crystal-clear waters and luxury accommodations.',
    itinerary: {
      first_day: 'Arrival in Maldives, transfer to resort',
      middle_days: {
        day_1: 'Snorkeling adventure',
        day_2: 'Diving excursion',
        day_3: 'Island hopping tour',
      },
      last_day: 'Spa day, departure',
    },
    itineraryTitles: {
      first_day: 'Arrival Day',
      middle_days: {
        day_1: 'Day 1: Underwater Exploration',
        day_2: 'Day 2: Deep Dive',
        day_3: 'Day 3: Island Adventure',
      },
      last_day: 'Departure Day',
    },
  },
];
